import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [input, setInput] = useState(1);
  const [inputError, setInputError] = useState("");
  const maxValue = 1000;
  const handleChange = (e) => {
    if (e.target.value < maxValue) {
      setInput(e.target.value);
      setInputError("")
    } else {
      setInputError(`Please enter the value below ${maxValue}`);
    }
  };
  const increment = () => {
    setInput(input < maxValue ? input + 1 : input);
  };
  const decrement = () => {
    setInput(input > 0 ? input - 1 : input);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Increment Decrement Counter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ display: "flex", fontSize: "21px" }}>
          <div
            style={{
              border: "1px solid #B24242",
              borderRadius: "10px 0px 0px 10px",
              width: "60px",
              textAlign: "center",
              padding: "15px",
              color: "#B24242",
              fontWeight: "900",
            }}
            onClick={decrement}
          >
            -
          </div>
          <input
            style={{
              borderLeftStyle: "none",
              borderRightStyle: "none",
              borderBottom: "1px solid #B24242",
              borderTop: "1px solid #B24242",
              width: "60px",
              background: "#FBE8E8",
              textAlign: "center",
              fontWeight: "900",
              color: "#B24242",
            }}
            value={input}
            onChange={handleChange}
            type="number"
          />
          <div
            style={{
              border: "1px solid #B24242",
              borderRadius: "0px 10px 10px 0px",
              // height: "56px",
              width: "60px",
              textAlign: "center",
              padding: "15px",
              color: "#fff",
              background: "#B24242",
              fontWeight: "900",
            }}
            onClick={increment}
          >
            +
          </div>
        </div>
        {inputError && <span style={{marginTop:"20px",color:"red"}}>{inputError}</span>}
      </main>
    </div>
  );
}
